name: Schedule Update
on:
  schedule:
    - cron: '0 11 * * *'  # Runs at 06:00 EST (11:00 UTC) every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-csv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas beautifulsoup4
        
    - name: Run update script
      run: python schedule-updater.py
        
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add 2025_schedule.csv
        git diff --staged --quiet || (git commit -m "Auto-update basketball schedule" && git push)